\c appatite_db;

DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS restaurants cascade;
DROP TABLE IF EXISTS followers cascade;
DROP TABLE IF EXISTS favorites cascade;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS reaction;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  fname VARCHAR(255),
  lname VARCHAR(255),
  username VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  about_me VARCHAR(255),
  auth INTEGER DEFAULT 1,
  loc VARCHAR(255),
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  rating INTEGER DEFAULT 0,
  cuisine VARCHAR(255),
  img_src VARCHAR(255),
  loc VARCHAR(255),
  creator VARCHAR(255) DEFAULT 'yelp',
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE followers (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(255) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  follower_name VARCHAR(255) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  username VARCHAR(255),
  restaurant_id INTEGER REFERENCES restaurants(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  restaurant_name VARCHAR(255),
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE reviews (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  username VARCHAR(255),
  restaurant_id INTEGER REFERENCES restaurants(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  restaurant_name VARCHAR(255),
  content VARCHAR(700),
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON users (username);
CREATE INDEX ON restaurants (name);
